name: Receta Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  test_la_receta: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dev dependencies
        run: pip install -r requirements.txt
      - name: Test la receta sugerida
        run: | 
          pytest -q test_receta.py 
